[package]
name = "sputnikvm-cli"
version = "0.6.0"
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>"]
description = "SputnikVM CLI"
repository = "https://github.com/ethereumproject/sputnikvm"

[[bin]]
name = "sputnikvm"

[dependencies]
sputnikvm = { path = ".." }
gethrpc = { path = '../gethrpc' }
clap = "2.22"
serde_json = "0.9"
